import org.eclipse.jgit.api.Git

group = "com.michaeljperri.flutter_sequencer"
version = "1.0-SNAPSHOT"

buildscript {
    ext.kotlin_version = "2.1.0"
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath("com.android.tools.build:gradle:8.9.1")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version")
        classpath("org.eclipse.jgit:org.eclipse.jgit:6.9.0.202403050737-r")
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: "com.android.library"
apply plugin: "kotlin-android"

android {
    namespace = "com.michaeljperri.flutter_sequencer"

    compileSdk = 36

    compileOptions {
        // 原本套件用 JavaVersion.VERSION_17
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    kotlinOptions {
        // 原本套件用 JavaVersion.VERSION_17
        jvmTarget = JavaVersion.VERSION_11
    }

    sourceSets {
        main.java.srcDirs += "src/main/kotlin"
        test.java.srcDirs += "src/test/kotlin"
    }

    defaultConfig {
        minSdk = 24
        externalNativeBuild {
            cmake {
                cppFlags '-std=c++17', '-frelaxed-template-template-args'
            }
        }
    }

    lint {
        disable 'InvalidPackage'
    }

    // ndkVersion "28.0.12674087" // 原本套件用的
    externalNativeBuild {
        cmake {
            // version "3.22.1" // 原本套件就已經"註解掉"了這行
            path "CMakeLists.txt"
        }
    }

    dependencies {
        testImplementation("org.jetbrains.kotlin:kotlin-test")
        testImplementation("org.mockito:mockito-core:5.0.0")
    }

    testOptions {
        unitTests.all {
            useJUnitPlatform()

            testLogging {
               events "passed", "skipped", "failed", "standardOut", "standardError"
               outputs.upToDateWhen {false}
               showStandardStreams = true
            }
        }
    }
}

tasks.register('cloneThirdPartyRepos') {
    doLast {
        cloneThirdPartyRepo('oboe', 'https://github.com/google/oboe', '06ec23e4f6bc00ba7eea9b84e299f9200a598838')
        cloneThirdPartyRepo('TinySoundFont', 'https://github.com/schellingb/TinySoundFont.git', 'bf574519e601202c3a9d27a74f345921277eed39')
    }
}

preBuild.dependsOn cloneThirdPartyRepos

void cloneThirdPartyRepo(String name, String uri, String commit) {
    def dir = new File("$projectDir/third_party/$name")
    if (!dir.exists()) {
        dir.mkdirs()
        def repo = Git.cloneRepository()
                .setDirectory(dir)
                .setURI(uri)
                .setRemote('origin')
                .setCloneSubmodules(true)
                .call()

        repo.checkout().setName(commit).call()
        repo.submoduleUpdate()
        repo.submoduleInit()
    }
}
